### ISSUE TITLE
impressive work! what's the Image Control means?

### ISSUE THREAD

**Issue by Madeline-hyh** [zyhrainbow/Diff-Restorer#2]
It's a great job. I'm very interested in your work. But I have a small question. I am not sure what Image Control stands for in the article, is it controlnet?

**Comment by zyhrainbow** [comment]
Yes, it has the same architecture as the ControlNet

**Comment by Madeline-hyh** [comment]
Thank you very much for your patient reply~

**Comment by Madeline-hyh** [comment]
Then I have a small question, looking forward to your reply: the feature dimension of the Control Encoder should be [B,C,H,W], and the input feature of the controlnet should be [B,L,C], so do you use MLP or other feature transformation in this process?

**Comment by zyhrainbow** [comment]
Sorry, I can not understand the question very clearly. The control encoder generate the downsampled feature which is align with the latent code and send to controlnet directly. Ihope this can help you~
