### ISSUE TITLE
Question about semantic branch

### ISSUE THREAD

**Issue by icuGrey** [zyhrainbow/Diff-Restorer#3]
Thank you for your great work! I have a question regarding the semantic branch of the network. Specifically, I’m interested in how the parameters of the semantic branch are updated to ensure that its output aligns with its dual purposes.

**Comment by zyhrainbow** [comment]
We design a degradation-aware guidance loss to guide the networkin learning useful degradation information and for the semantic branch，we hope to use stable diffusion prior so when we froze the unet backbone， the semantic embedding will be got implicitly under the guidance of diffusion loss. I hope this can help you. Thank you very much~

**Comment by icuGrey** [comment]
Thank you for your quick reply! It’s really helpful and addresses my question
